version: '3'

services:
  backend:
    build: ./backend/
    container_name: backend
    ports:
      - "42422:42422"
  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "42421:42421"
